# trusty dist provides a modern build chain (as opposed to 'precise' dist)
# which absolves us from having to install compilers and stuff
sudo: required
dist: trusty

language: node_js

matrix:
  fast_finish: true

before_install: scripts/travis-before-install.sh

before_script: scripts/travis-before-script.sh

jobs:
  include:
    - stage: lint
      node_js: '8'
      env: TARGET=lint
      script: npm start $TARGET
    - stage: test
      node_js: '9'
      env: TARGET=test.node COVERAGE=true
      script: npm start $TARGET
    - node_js: '8'
      env: TARGET=test.node
      script: npm start $TARGET
    - node_js: '6'
      env: TARGET=test.node
      script: npm start $TARGET
    - node_js: '4'
      env: TARGET=test.node
      script: npm start $TARGET
    - node_js: '8'
      env: TARGET=test.browser
      script: npm start $TARGET

stages:
  - lint
  - test

after_success: npm start coveralls

addons:
  artifacts:
    paths:
      - .karma/
      - ./mocha.js
  sauce_connect: true
  chrome: stable
cache:
  directories:
    - ~/.npm
