name: 'Windows CI'
on:
  pull_request:
  push:
    branches:
      - master
      - windows-ci
      - release/*

jobs:
  env:
    CI: true
  smoke:
    runs-on: ubuntu-latest
    steps:
      - env:
        NODE_ENV: production
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: npm install
      - name: NODE_ENV
        run: echo $NODE_ENV
      - name: smoke test
        run: ./bin/mocha --no-config --reporter spec test/sanity/sanity.spec.js

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: lint
        run: npm start lint

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
        node-version: [10.x, 12.x, 13.x]
    runs-on: ${{ matrix.platform }}
    steps:
      #      - uses: actions/checkout@v2
      - name: Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
